# Generated by Django 5.2.4 on 2025-08-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartwatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_uid', models.UUIDField(unique=True)),
                ('device_name', models.CharField(default='default-smartwatch', max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_oxygen', models.FloatField(blank=True, null=True)),
                ('stress_level', models.FloatField(blank=True, null=True)),
                ('sleep_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('sleep_quality', models.FloatField(blank=True, null=True)),
                ('body_temperature', models.FloatField(blank=True, null=True)),
                ('skin_conductance', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='smartwatch_streams.smartwatchsession')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('sitting', 'Sitting'), ('standing', 'Standing'), ('sleeping', 'Sleeping'), ('workout', 'Workout'), ('unknown', 'Unknown')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='smartwatch_streams.smartwatchsession')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('accelerometer', 'Accelerometer'), ('gyroscope', 'Gyroscope'), ('gps', 'GPS'), ('step_counter', 'Step Counter'), ('sleep', 'Sleep Tracking'), ('activity', 'Activity Recognition')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('values', models.JSONField(default=dict)),
                ('accuracy', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('kafka_offset', models.BigIntegerField(blank=True, null=True)),
                ('kafka_partition', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='smartwatch_streams.smartwatchsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'sensor_type', 'timestamp'], name='smartwatch__session_afdbbb_idx'), models.Index(fields=['timestamp'], name='smartwatch__timesta_f382c1_idx')],
            },
        ),
    ]
