# Generated by Django 5.2.4 on 2025-08-05 12:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AriaStreamingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("vrs_file_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("STREAMING", "Streaming"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UnifiedSensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_timestamp_ns", models.BigIntegerField()),
                ("stream_id", models.CharField(max_length=20)),
                ("stream_label", models.CharField(max_length=50)),
                ("sensor_type", models.CharField(max_length=20)),
                ("data_payload", models.JSONField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aria_sessions.ariastreamingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["device_timestamp_ns"],
            },
        ),
    ]
