# Generated by Django 5.2.4 on 2025-08-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebcamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_uid', models.UUIDField(unique=True)),
                ('device_name', models.CharField(default='default-webcam', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WebcamFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('fps', models.FloatField(default=30.0)),
                ('format', models.CharField(default='RGB', max_length=10)),
                ('frame_path', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('kafka_offset', models.BigIntegerField(blank=True, null=True)),
                ('kafka_partition', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='webcam_streams.webcamsession')),
            ],
        ),
        migrations.CreateModel(
            name='WebcamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('motion', 'Motion Detection'), ('face', 'Face Detection'), ('object', 'Object Detection'), ('activity', 'Activity Recognition')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.FloatField(default=0.0)),
                ('results', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='webcam_streams.webcamframe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='webcam_streams.webcamsession')),
            ],
        ),
    ]
